stages:
  - prepare
  - build
  - test
  - publish

variables:
  VIRTER_VERSION: v0.14.3
  VMSHED_VERSION: v0.14.0
  BUILD_HELPERS_VERSION: dfbf85c26dd39ad1a88807b01fda1dc1d536abbb

prepare:
  image: nexus.at.linbit.com:5000/build-helpers:${BUILD_HELPERS_VERSION}
  stage: prepare
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  variables:
    # git describe needs full history access
    GIT_DEPTH: 0
    # git describe does not need the submodule
    GIT_SUBMODULE_STRATEGY: none
  script:
    - SEMVER="$(semver-from-git.py)"
    - echo "SEMVER=${SEMVER}" >> .ci-build.env
    - echo "TAG=v${SEMVER/+/-}" >> .ci-build.env
    - . /usr/local/bin/gitlab-utils.sh
    - ci_prepare_tools
    - ci_fetch_binary virter virter-$VIRTER_VERSION https://github.com/LINBIT/virter/releases/download/$VIRTER_VERSION/virter-linux-amd64
    - ci_fetch_binary vmshed vmshed-$VMSHED_VERSION https://github.com/LINBIT/vmshed/releases/download/$VMSHED_VERSION/vmshed-linux-amd64
  artifacts:
    paths:
      - bin
      - download
    reports:
      dotenv: .ci-build.env

.prepare-vm:
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  tags:
    - libvirt
  cache:
    paths:
      - download
  script:
    - export PATH=$CI_PROJECT_DIR/bin:$PATH
    - ln -snf $DOCKER_AUTH_CONFIG_FILE $HOME/.docker/config.json
    - cd test/vms
    - >
      virter image build
      nexus.at.linbit.com:5000/vm/$BASE:latest
      nexus.at.linbit.com:5000/linstor-csi-builder/vm/$NAME:$CI_COMMIT_REF_SLUG
      --pull-policy=Always
      --push
      --build-id "$(git rev-list -1 --abbrev-commit HEAD ${NAME}.provision.toml)"
      -p ${NAME}.provision.toml
      ${EXTRA_BUILD_ARGS}

prepare-sanity-vm:
  extends: .prepare-vm
  variables:
    NAME: sanity
    BASE: ubuntu-focal
    EXTRA_BUILD_ARGS: "--set values.LinstorRepo=$LINBIT_REGISTRY_URL/repository/packages-linbit-com"

prepare-e2e-vm:
  extends: .prepare-vm
  variables:
    NAME: e2e
    BASE: centos-7
    EXTRA_BUILD_ARGS: "--set values.DockerRegistryMirror=$DOCKER_REGISTRY_MIRROR"

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_DEPTH: 1
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  tags:
    - multiarch
  script:
    # Use NOCACHE=true for release builds
    - if [ -n "${CI_COMMIT_TAG}" ]; then NOCACHE=true ; else NOCACHE=false ; fi
    - docker login -u ${LINBIT_REGISTRY_USER} -p ${LINBIT_REGISTRY_PASSWORD} ${LINBIT_DOCKER_REGISTRY}
    - docker buildx build --platform linux/amd64,linux/s390x --build-arg=REPO_SOURCE=${LINBIT_DOCKER_REGISTRY}/rhel-container-secrets:latest --pull --push -t "${LINBIT_DOCKER_REGISTRY}/linstor-csi:${TAG}" --no-cache="${NOCACHE}" .
    - echo "CSI_PLUGIN_IMAGE=${LINBIT_DOCKER_REGISTRY}/linstor-csi:${TAG}" > .build.env
  artifacts:
    reports:
      dotenv:
        - .build.env

build-tests:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  image: golang:1
  script:
    - make test/bin
  artifacts:
    paths:
      - test/bin

make-tar:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  image: golang:1
  script:
    - make bin-release ARCH="amd64 arm64 s390x ppc64le" SKIP_VERSION_CHECK=1 SEMVER=$SEMVER
  artifacts:
    paths:
      - "out/"

container_scanning:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    # No need to clone the repo, we exclusively work on artifacts.  See
    # https://docs.gitlab.com/ee/ci/runners/README.html#git-strategy
    GIT_STRATEGY: none
  script:
    - trivy --version
    - trivy client --exit-code 0 --format template --template "@/contrib/html.tpl" -o container-scan.html "$CSI_PLUGIN_IMAGE"
    # Prints full report
    - trivy client --exit-code 0 "$CSI_PLUGIN_IMAGE"
    # Fail on critical (unfixed) vulnerabilities
    - trivy client --exit-code 1 --ignore-unfixed --severity CRITICAL "$CSI_PLUGIN_IMAGE"
  # Ideally, we would use container_scanning for the artifact here. That is currently a paid feature, so we have to use code quality
  artifacts:
    when: always
    expose_as: "Container Scan"
    paths:
      - container-scan.html

.vmtest:
  stage: test
  tags:
    - libvirt
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  cache:
    paths:
      - download
  script:
    - export PATH=$CI_PROJECT_DIR/bin:$PATH
    - virter image pull linstor-csi-${NAME}-test-vm nexus.at.linbit.com:5000/linstor-csi-builder/vm/$NAME:$CI_COMMIT_REF_SLUG
    - vmshed --vms vms.${NAME}.toml --tests tests.${NAME}.toml ${VMSHED_ARGS}
  artifacts:
    name: ${NAME}-reports
    paths:
      - tests-out/
    reports:
      junit:
        - tests-out/**/*.xml

sanity-test:
  extends: .vmtest
  variables:
    NAME: sanity

e2e-test:
  extends: .vmtest
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == 'master'
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true
  timeout: 5h
  variables:
    NAME: e2e
    VMSHED_ARGS: --set values.LinstorCSIImage=${CSI_PLUGIN_IMAGE} --set values.DockerUsername=${TEST_DOCKER_USER} --set values.DockerPassword=${TEST_DOCKER_PASSWORD}

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - crane auth login -u $PUBLISH_REGISTRY_USER -p $PUBLISH_REGISTRY_PASSWORD $PUBLISH_REGISTRY
    - crane copy --platform linux/amd64 ${CSI_PLUGIN_IMAGE} ${PUBLISH_REGISTRY}/amd64/linstor-csi:${TAG}
    - crane copy --platform linux/s390x ${CSI_PLUGIN_IMAGE} ${PUBLISH_REGISTRY}/s390x/linstor-csi:${TAG}
    - crane tag ${PUBLISH_REGISTRY}/amd64/linstor-csi:${TAG} latest
    - crane tag ${PUBLISH_REGISTRY}/s390x/linstor-csi:${TAG} latest
