stages:
  - prepare
  - build
  - test
  - publish

variables:
  VIRTER_VERSION: v0.7.1
  VMSHED_VERSION: v0.8.1
  BUILD_HELPERS_VERSION: c25556713c0c6f10d153c9e8a4d45702ea916aff

prepare:
  image: nexus.at.linbit.com:5000/build-helpers:latest
  stage: prepare
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  variables:
    # git describe needs full history access
    GIT_DEPTH: 0
    # git describe does not need the submodule
    GIT_SUBMODULE_STRATEGY: none
  script:
    - SEMVER="$(semver-from-git.py)"
    - echo "SEMVER=${SEMVER}" >> .ci-build.env
    - echo "TAG=v${SEMVER/+/-}" >> .ci-build.env
  artifacts:
    reports:
      dotenv: .ci-build.env

.build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_DEPTH: 1
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  tags:
    - shell
  script:
    # Use NOCACHE=true for release builds
    - if [ -n "${CI_COMMIT_TAG}" ]; then NOCACHE=true ; else NOCACHE=false ; fi
    - docker login -u ${LINBIT_REGISTRY_USER} -p ${LINBIT_REGISTRY_PASSWORD} ${LINBIT_DOCKER_REGISTRY}
    - make update upload REGISTRY=${LINBIT_DOCKER_REGISTRY} TAG="${TAG}-${ARCH}" ARCH="${ARCH}" NOCACHE="${NOCACHE}"

build-amd64:
  extends: .build
  variables:
    ARCH: amd64
  tags:
    - shell

build-s390x:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG
  extends: .build
  variables:
    ARCH: s390x
  tags:
    - s390x

build-tests:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  image: golang:1
  script:
    - make test/bin
  artifacts:
    paths:
      - test/bin

sanity-test:
  stage: test
  tags:
    - libvirt
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  cache:
    paths:
      - download
  script:
    - |
      curl -sSfL -u gitlab-ci-token:$CI_JOB_TOKEN https://gitlab.at.linbit.com/linbit/build-helpers/-/archive/$BUILD_HELPERS_VERSION/ignored.tar.gz | tar -xvzf -
      mv build-helpers-* build-helpers
      . build-helpers/gitlab-utils.sh
    - |
      ci_prepare_tools
      ci_fetch_rq
      ci_fetch_binary virter virter-$VIRTER_VERSION https://github.com/LINBIT/virter/releases/download/$VIRTER_VERSION/virter-linux-amd64
      ci_fetch_binary vmshed vmshed-$VMSHED_VERSION https://github.com/LINBIT/vmshed/releases/download/$VMSHED_VERSION/vmshed-linux-amd64
    - virter image pull linstor-csi-sanity-test-vm -u ${SANITY_TEST_VM_IMAGE} >/dev/null 2>&1 || echo "image already exists"
    - vmshed --vms vms.toml --tests tests.toml
  artifacts:
    reports:
      junit:
        - tests-out/**/*.xml

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - crane auth login -u $PUBLISH_REGISTRY_USER -p $PUBLISH_REGISTRY_PASSWORD $PUBLISH_REGISTRY
    - crane copy ${LINBIT_DOCKER_REGISTRY}/linstor-csi:${TAG}-amd64 ${PUBLISH_REGISTRY}/amd64/linstor-csi:${TAG}
    - crane copy ${LINBIT_DOCKER_REGISTRY}/linstor-csi:${TAG}-s390x ${PUBLISH_REGISTRY}/s390x/linstor-csi:${TAG}
    - crane tag ${PUBLISH_REGISTRY}/amd64/linstor-csi:${TAG} latest
    - crane tag ${PUBLISH_REGISTRY}/s390x/linstor-csi:${TAG} latest
